.Dd August 11, 2021
.Dt AZURE-IMDS-QUERY 8
.Os
.Sh NAME
.Nm azure-imds-query
.Nd query the Azure Instance Metadata Service
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility queries the Azure Instance Metadata Service and extracts information.
It is primarily intended to be used with rc scripts.
.Pp
.Sh SEE ALSO
.Xr rc 8 ,
.Xr rc.conf 5 
